version: '3.5'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    deploy:
      resources:
        limits:
          memory: '1G'
    volumes:
      - type: volume
        source: esdata1
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.1.1
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    deploy:
      resources:
        limits:
          memory: '1G'
    volumes:
      - type: bind
        source: ./logstash/pipeline/
        target: /usr/share/logstash/pipeline/
    ports:
      - 5000:5000
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.1.1
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: volume
        source: beat-logs
        target: /var/log/
    networks:
      - elk
    depends_on:
      - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    deploy:
      resources:
        limits:
          memory: '1G'
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  esdata1:
  beat-logs:

networks:
  elk:

